export const sentences = [
  {
    partial_sentence: "The cat sat on the ____.",
    first_word: "mat",
    second_word: "hat",
    correct_word: "mat",
    sentence: "The cat sat on the mat.",
  },
  {
    partial_sentence: "She drank a cup of ____ tea.",
    first_word: "green",
    second_word: "blue",
    correct_word: "green",
    sentence: "She drank a cup of green tea.",
  },
  {
    partial_sentence: "The sun rises in the ____.",
    first_word: "west",
    second_word: "east",
    correct_word: "east",
    sentence: "The sun rises in the east.",
  },
  {
    partial_sentence: "He plays the ____ every evening.",
    first_word: "piano",
    second_word: "guitar",
    correct_word: "piano",
    sentence: "He plays the piano every evening.",
  },
  {
    partial_sentence: "They went to the ____ to swim.",
    first_word: "beach",
    second_word: "mountain",
    correct_word: "beach",
    sentence: "They went to the beach to swim.",
  },
  {
    partial_sentence: "She loves to read ____ books.",
    first_word: "mystery",
    second_word: "history",
    correct_word: "mystery",
    sentence: "She loves to read mystery books.",
  },
  {
    partial_sentence: "The flowers in the garden are ____.",
    first_word: "blooming",
    second_word: "falling",
    correct_word: "blooming",
    sentence: "The flowers in the garden are blooming.",
  },
  {
    partial_sentence: "He is writing a ____ story.",
    first_word: "short",
    second_word: "long",
    correct_word: "short",
    sentence: "He is writing a short story.",
  },
  {
    partial_sentence: "The bird flew over the ____.",
    first_word: "tree",
    second_word: "house",
    correct_word: "tree",
    sentence: "The bird flew over the tree.",
  },
  {
    partial_sentence: "They are painting the ____.",
    first_word: "wall",
    second_word: "floor",
    correct_word: "wall",
    sentence: "They are painting the wall.",
  },
];
