export const sentences = [
  {
    partial_sentence:
      "Umm, okay, okay, look. I took this picture from your fridge. Okay, because I know that this is my Father. Yeah, this is Frank Buffay and you are standing ______ there next to him. Now, look I deserve to know where I came from. All right? So if you can help me find my Father then you should! Otherwise, youre just mean! So, just tell me the truth!",
    first_word: "correct",
    second_word: "right",
    correct_word: "correct",
    sentence:
      "Umm, okay, okay, look. I took this picture from your fridge. Okay, because I know that this is my Father. Yeah, this is Frank Buffay and you are standing correct there next to him. Now, look I deserve to know where I came from. All right? So if you can help me find my Father then you should! Otherwise, youre just mean! So, just tell me the truth!",
  },
  {
    partial_sentence: "She felt ____ after the long run.",
    first_word: "tired",
    second_word: "exhausted",
    correct_word: "tired",
    sentence: "She felt tired after the long run.",
  },
  {
    partial_sentence: "The ____ flowers were admired by all.",
    first_word: "beautiful",
    second_word: "gorgeous",
    correct_word: "beautiful",
    sentence: "The beautiful flowers were admired by all.",
  },
  {
    partial_sentence: "He gave a ____ answer during the interview.",
    first_word: "clear",
    second_word: "concise",
    correct_word: "concise",
    sentence: "He gave a concise answer during the interview.",
  },
  {
    partial_sentence: "The ____ house stood on the hill.",
    first_word: "large",
    second_word: "spacious",
    correct_word: "large",
    sentence: "The large house stood on the hill.",
  },
  {
    partial_sentence: "They were ____ about the outcome of the match.",
    first_word: "excited",
    second_word: "eager",
    correct_word: "excited",
    sentence: "They were excited about the outcome of the match.",
  },
  {
    partial_sentence: "The ____ path led to the beach.",
    first_word: "narrow",
    second_word: "thin",
    correct_word: "narrow",
    sentence: "The narrow path led to the beach.",
  },
  {
    partial_sentence: "She gave a ____ smile after hearing the news.",
    first_word: "happy",
    second_word: "joyful",
    correct_word: "happy",
    sentence: "She gave a happy smile after hearing the news.",
  },
  {
    partial_sentence: "He wore a ____ jacket in the cold weather.",
    first_word: "thick",
    second_word: "heavy",
    correct_word: "thick",
    sentence: "He wore a thick jacket in the cold weather.",
  },
  {
    partial_sentence: "The ____ cat curled up on the sofa.",
    first_word: "soft",
    second_word: "plush",
    correct_word: "soft",
    sentence: "The soft cat curled up on the sofa.",
  },
];

export const gameHistory = [
  {
    date: "2024-09-15",
    time: "10:30 AM",
    difficulty: "Low",
    correctAnswers: 8,
    totalQuestions: 10,
  },
  {
    date: "2024-09-14",
    time: "4:15 PM",
    difficulty: "Medium",
    correctAnswers: 7,
    totalQuestions: 10,
  },
  {
    date: "2024-09-13",
    time: "2:20 PM",
    difficulty: "High",
    correctAnswers: 1,
    totalQuestions: 10,
  },
  {
    date: "2024-09-12",
    time: "11:00 AM",
    difficulty: "Low",
    correctAnswers: 10,
    totalQuestions: 10,
  },
  {
    date: "2024-09-11",
    time: "9:45 AM",
    difficulty: "Medium",
    correctAnswers: 9,
    totalQuestions: 10,
  },
  {
    date: "2024-09-10",
    time: "8:30 PM",
    difficulty: "High",
    correctAnswers: 1,
    totalQuestions: 10,
  },
  {
    date: "2024-09-09",
    time: "7:00 PM",
    difficulty: "Low",
    correctAnswers: 9,
    totalQuestions: 10,
  },
  {
    date: "2024-09-08",
    time: "6:15 PM",
    difficulty: "Medium",
    correctAnswers: 6,
    totalQuestions: 10,
  },
  {
    date: "2024-09-07",
    time: "5:45 PM",
    difficulty: "High",
    correctAnswers: 1,
    totalQuestions: 10,
  },
  {
    date: "2024-09-06",
    time: "4:10 PM",
    difficulty: "Medium",
    correctAnswers: 8,
    totalQuestions: 10,
  },
];

export const guideSentence = {
  first_word: "great",
  first_sentence: "That is great Joe!",
  second_word: "grand",
  second_sentence: "The grand staircase was the centerpiece of the mansion.",
  partial_sentence: "Our guys a ______ dancer!",
  sentence: "Our guys a great dancer!",
  correct_word: "great",
};
