export const sentences = [
  {
    partial_sentence: "The ____ man greeted us warmly.",
    first_word: "kind",
    second_word: "polite",
    correct_word: "kind",
    sentence: "The kind man greeted us warmly.",
  },
  {
    partial_sentence: "She felt ____ after the long run.",
    first_word: "tired",
    second_word: "exhausted",
    correct_word: "tired",
    sentence: "She felt tired after the long run.",
  },
  {
    partial_sentence: "The ____ flowers were admired by all.",
    first_word: "beautiful",
    second_word: "gorgeous",
    correct_word: "beautiful",
    sentence: "The beautiful flowers were admired by all.",
  },
  {
    partial_sentence: "He gave a ____ answer during the interview.",
    first_word: "clear",
    second_word: "concise",
    correct_word: "concise",
    sentence: "He gave a concise answer during the interview.",
  },
  {
    partial_sentence: "The ____ house stood on the hill.",
    first_word: "large",
    second_word: "spacious",
    correct_word: "large",
    sentence: "The large house stood on the hill.",
  },
  {
    partial_sentence: "They were ____ about the outcome of the match.",
    first_word: "excited",
    second_word: "eager",
    correct_word: "excited",
    sentence: "They were excited about the outcome of the match.",
  },
  {
    partial_sentence: "The ____ path led to the beach.",
    first_word: "narrow",
    second_word: "thin",
    correct_word: "narrow",
    sentence: "The narrow path led to the beach.",
  },
  {
    partial_sentence: "She gave a ____ smile after hearing the news.",
    first_word: "happy",
    second_word: "joyful",
    correct_word: "happy",
    sentence: "She gave a happy smile after hearing the news.",
  },
  {
    partial_sentence: "He wore a ____ jacket in the cold weather.",
    first_word: "thick",
    second_word: "heavy",
    correct_word: "thick",
    sentence: "He wore a thick jacket in the cold weather.",
  },
  {
    partial_sentence: "The ____ cat curled up on the sofa.",
    first_word: "soft",
    second_word: "plush",
    correct_word: "soft",
    sentence: "The soft cat curled up on the sofa.",
  },
];
