import { StyleSheet, Dimensions } from "react-native";

export const s = StyleSheet.create({
  img_background: {
    resizeMode: "cover",
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  pageContainer: {
    padding: 20,
    alignItems: "center",
  },
  exampleContainer: {
    marginTop: 50,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 20,
    padding: 10,
  },
  wordText: {
    fontSize: 24,
    marginBottom: 10,
    color: "white",
    textDecorationLine: "underline",
  },
  introductionText: {
    fontSize: 18,
    marginVertical: 5,
    color: "white",
  },
  sentenceText: {
    fontSize: 23,
    marginVertical: 5,
    color: "#a4f2fc",
  },
  questionContainer: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 20,
    padding: 10,
  },
  questionText: {
    fontSize: 30,
    marginBottom: 20,
    color: "white",
  },
  optionsContainer: {
    flexDirection: "row",
    width: "100%",
    marginVertical: 20,
    marginTop: 60,
  },
  optionButton: {
    marginHorizontal: 20,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "white",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,

    elevation: 24,
  },
  optionText: {
    fontSize: 18,
    color: "#333",
    fontWeight: "bold",
    color: "white",
  },
  nextButton: {
    marginTop: 70,
    padding: 10,
    backgroundColor: "#50a5ffd2",
    borderRadius: 5,
  },
  nextButtonText: {
    color: "#fff",
    fontSize: 18,
  },
  conclusionText: {
    fontSize: 22,
    textAlign: "center",
    marginBottom: 20,
  },
  exitButton: {
    position: "absolute",
    width: 50,
    height: 50,
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 38,
    left: 30,
    bottom: 30,
  },
  exitIconView: {
    marginTop: 10,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  exitGameIcon: {
    height: "75%",
    width: "75%",
    resizeMode: "contain",
  },
  explanationContainer: {
    padding: 20,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
    borderRadius: 20,
    padding: 10,
    margin: 15,
  },
  explanationText: {
    justifyContent: "center",
    alignItems: "center",
    color: "white",
    fontSize: 22,
  },
  poweredByTxt: {
    alignSelf: "center",
    color: "white",
    marginBottom: 10,
  },
  gptTitle: {
    flexDirection: "row",
  },
  poweredByImage: {
    width: 40,
    height: 40,
    resizeMode: "contain",
    color: "white",
    marginHorizontal: 10,
  },
});
